spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration

cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIAYELNJVNGQ64XO37E
      secret-key: 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
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/559111842637/MyFIFOQueue.fifo
